version: "3.9"
services:
  db:
    image: postgres:12.9-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
      # - ./db/raw_data:/data
      # - ./db/sql_scripts:/docker-entrypoint-initdb.d/